version: '3'
services:
  web:
    image: nginx
    volumes:
    - ./Docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    depends_on:
    - api
  api:
    build:
      context: Docker/api
    volumes:
      - ./:/var/www
      - ./Docker/api/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini